"""empty message

Revision ID: aa27a9a115c2
Revises:
Create Date: 2026-03-23 06:59:05.862680

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa27a9a115c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.alter_column(
            "original",
            existing_type=sa.VARCHAR(length=1000),
            type_=sa.String(length=100000),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.alter_column(
            "original",
            existing_type=sa.String(length=100000),
            type_=sa.VARCHAR(length=1000),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
